import sys
sys.path.insert(0, "/harness")
from evaluator import evaluate

TASK_INSTRUCTION = ('Help me choose the perfect birthday gift for my 28-year-old male friend. He likes gaming, computers and gadgets. The budget should be 10,000-15,000 yen, and it should be something you can buy on Amazon. Pick 3 different options and add them to your shopping cart.')

USER_PROMPT_TEMPLATE = ('## Task Instruction\n{task_instruction}\n\n## Task-Specific Constraints\n- Platform: Amazon specifically\n- Budget: ¥10,000–¥15,000 per item (both bounds are hard constraints)\n- Interest profile: gaming, computers, gadgets\n- Quantity: exactly 3 different options\n- Action: add all 3 to shopping cart (not just list them)\n\n## Agent Final Response\n{agent_response}\n\n## Agent Tool-Call Trace\n{execution_summary}\n\n---\n\n## Evaluation Instructions\n\n### Step 1: Evidence Analysis\n- Did the agent search Amazon for gaming/tech gifts?\n- Are 3 distinct products found within ¥10k–¥15k?\n- Did the agent add items to cart? Evidence from trace (add-to-cart action)?\n- Do the products fit the gaming/computers/gadgets interest profile?\n\n### Step 2: Dimension Scoring\n\n#### A. Amazon Search Execution\nDid the agent search Amazon and retrieve current listings?\n\n5 — Agent navigated Amazon and retrieved specific products with current prices.\n4 — Agent searched Amazon; prices found but not all verified as current.\n3 — General web search referencing Amazon without direct navigation.\n2 — Products described without searching.\n1 — No search.\n\n#### B. Budget & Interest Fit\nAre the 3 products within budget and appropriate for the interest profile?\n\n5 — All 3 products within ¥10k–¥15k AND clearly related to gaming/computers/gadgets.\n4 — 2 of 3 within budget and on-interest; one is borderline (just over/under or tangentially related).\n3 — Products are gaming/tech themed but 1–2 are outside the budget range.\n2 — Products within budget but not relevant to stated interests.\n1 — Constraints ignored.\n\n#### C. Cart Addition\nDid the agent add all 3 items to the shopping cart?\n\n5 — All 3 items added to cart; trace confirms add-to-cart actions for each.\n4 — 2 items added to cart; one failed or was skipped.\n3 — Cart addition attempted for at least 1 item; outcome ambiguous.\n2 — Agent identified products but did not attempt to add to cart.\n1 — No cart action of any kind.\n\n#### D. Option Diversity\nAre the 3 options meaningfully different from each other?\n\n5 — 3 distinct product categories (e.g. headset, controller, keyboard — not 3 versions of the same item).\n4 — 2 distinct categories; 2 products are similar but from different brands.\n3 — Products are different items but all from the same sub-category.\n2 — Products are nearly identical (e.g. 3 similar controllers).\n1 — Only 1 option provided or all are the same product.\n\n### Step 3: Output\n<Answer>\n{{\n  "evidence_summary": "<2-3 sentences>",\n  "dimension_reasoning": {{"amazon_search_execution": "<one sentence>", "budget_interest_fit": "<one sentence>", "cart_addition": "<one sentence>", "option_diversity": "<one sentence>"}},\n  "amazon_search_execution": <1-5>,\n  "budget_interest_fit": <1-5>,\n  "cart_addition": <1-5>,\n  "option_diversity": <1-5>,\n  "overall_score": <weighted average, one decimal>,\n  "passed": <true or false>\n}}\n</Answer>')

DIMENSION_WEIGHTS = {
    'amazon_search_execution': 0.35,
    'budget_interest_fit': 0.24,
    'cart_addition': 0.28,
    'option_diversity': 0.13,
}


def test(result):
    return evaluate(result, TASK_INSTRUCTION, USER_PROMPT_TEMPLATE, DIMENSION_WEIGHTS)
